name: Continuos Integration

on:
  pull_request:
      branches:
        ['main']


jobs:
  continuos-integration:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/chechout@v3
    - name: Using Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.
    - name: run install, build
      run: |
        npm install
        npm run build
