version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Mapeia a porta 3000 do contêiner para a porta 3000 do host
    environment:
      - PORT_URI=http://localhost:3000

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"  # Mapeia a porta 4000 do contêiner para a porta 4000 do host
    environment:
      - MONGODB_URI=mongodb+srv://CatConnect:catConnect2023@bancocatconnect.qqj0z5w.mongodb.net/?retryWrites=true&w=majority&appName=AtlasApp
      - PORT_SERVER=4000
