# Use uma imagem base do Node.js 16
FROM node:16

# Diretório de trabalho
WORKDIR /app

# Copie os arquivos do frontend
COPY frontend/package*.json ./

# Instale as dependências do frontend
RUN npm install

# Copie o restante dos arquivos do frontend
COPY frontend .

# Exponha a porta para o frontend
EXPOSE 3000

# Comando para iniciar o aplicativo frontend
CMD ["npm", "start"]