version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - project-rede

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    ports:
      - "4000:4000"
    networks:
      - project-rede

networks:
  project-rede:
    driver: bridge
